#!/bin/bash
clear

cat << EOF
-------------------------------------
Configuration DHCP
-------------------------------------

IP Forwarding : Activation..
-uncomment line in "/etc/sysctl.conf"

EOF

#Modification du fichier /etc/sysctl.conf

grep "#net.ipv4.ip_forward=1" /etc/sysctl.conf
if [ "$?" = 0 ]
then 
	sed -i 's/#net.ipv4.ip_forward=1.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
	echo "Done."
else
	echo "Already done"
fi

echo "Nat activation.."
iptables -t nat -A POSTROUTING -o enp -j MASQUERADE
echo "Done."

echo "Installing dhcp.."
apt-get install isc-dhcp-server -y > /dev/null

#Begin asking user input

echo "Entrez l'IP de votre serveur DHCP: (192.168.0.1)"
read ip

if [ "$ip" = "" ]
then
	ip="192.168.0.1"
fi
split_ip=$(echo $ip | tr ";" "\n")

echo "IP choisie: $ip"

#Split ip into an array
split_ip=$(echo $ip | tr ";" "\n")

echo "Entrez le pool d'adresse IP: (10-50)"
read pool

if [ "$pool" = "" ]
then
	pool="10-50"
fi

split_pool=$(echo $pool | tr "-" "\n")

echo "Pool choisi: ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.${split_pool[0]} --> ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.${split_pool[1]}"

#Create DHCP file
echo "Creating dhcp config file.."
echo "
default-lease-time 600;
max-lease-time 7200;
option subnet-mask 255.255.255.0;
subnet $ip netmask 255.255.255.0 {
	range ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.${POOL[0]} ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.${POOL[1]};
	option routeurs ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.254;
}
" > /etc/dhcp/dhcpd.conf
echo "done."
#DNS pour plus tard : option domain-name-servers ${split_ip[0]}.${split_ip[1]}.${split_ip[2]}.1;
