#!/bin/bash

id="`id -u`"
if [ "$id" = 0 ]
then
	echo "Super user root confirmed !"
else
	echo "You don't have enough permission to do that."
	exit 1
fi

echo "IP Forwarding : Activation.."
echo "-uncomment line in "/etc/sysctl.conf""

grep "#net.ipv4.ip_forward=1" /etc/sysctl.conf
if [ "$?" = 0 ]
then 
	sed -i 's/#net.ipv4.ip_forward=1.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
	echo "done."
else
	echo "Already done"
fi

echo "Network interfaces liste :"
ip a | grep UP | cut -d " " -f 2 | cut -d ":" -f 1
read -p "Interface name : " uservar

echo "Nat activation.."
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
echo "done."

echo "Installing dhcp.."
apt-get install isc-dhcp-server -y > /dev/null

if [ "$?" = 0 ]
then
	echo "done."
else
	echo "error"
	exit 1
fi

#Begin asking user input
read -p "Entrez l'IP de votre serveur DHCP (192.168.0.1) :" ip

if [ "$ip" == "" ]
then
	ip="192.168.0.1"
fi
echo "IP choisie: $ip"

#Split ip into an array
IFS='.' read -ra ADDR <<< "$ip"
read -p "Entrez le pool d'adresse IP (10-50) :" pool

if [ "$pool" == "" ]
then
	pool="10-50"
fi

IFS='-' read -ra POOL <<< "$pool"
echo "Pool choisi : ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.${POOL[0]} --> ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.${POOL[1]}"

#Create DHCP file
echo "Creating dhcp config file.."
echo "
default-lease-time 600;
max-lease-time 7200;

option subnet-mask 255.255.255.0;
subnet $ip netmask 255.255.255.0 {
	range ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.${POOL[0]} ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.${POOL[1]};
	option routeurs ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.254;
}
" > /etc/dhcp/dhcpd.conf
echo "done."
#DNS pour plus tard : option domain-name-servers ${ADDR[0]}.${ADDR[1]}.${ADDR[2]}.1;
