#!/bin/bash

id=co="`id -u`"
if [ "$id" = 0 ]
then
	echo "Super user root confirmed !"
else
	echo "You don't have enough permission to do that."
	exit 1
fi

echo "IP Forwarding : Activation.."
echo "-uncomment line in "/etc/sysctl.conf""

grep "#net.ipv4.ip_forward=1" /etc/sysctl.conf
if [ "$?" = 0 ]
then 
	sed -i 's/#net.ipv4.ip_forward=1.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
	echo "done."
else
	echo "Already done"
fi

echo "Network interfaces liste :"
ifconfig | egrep '^[^ ]' |  awk '{print $1}'
read -p 'Interface name : ' uservar

echo "Nat activation.."
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
echo "done."

echo "Installing dhcp.."
apt-get install isc-dhcp-server -y > /dev/null

if [ "$?" = 0 ]
then
	echo "done."
else
	echo "error"
	exit 1
fi

